version: "3.9"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - XDEBUG_MODE=coverage
      - MEMORY_LIMIT=512M
    volumes:
      - .:/app
    depends_on:
      composer:
        condition: service_completed_successfully
  composer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: composer
    command: ["install"]
  infection:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: ./vendor/bin/infection
    command: ["--threads=4"]
